	layout split
	focus cmd
	target remote localhost:2331
	monitor endian little
	monitor reset
	monitor halt
	monitor semihosting enable
	monitor speed 1000
	monitor loadbin ./.build/EFM32GG_STK3700/GCC_ARM/mpu_interface.bin 0
	monitor flash device = EFM32GG990F1024
	load ./.build/EFM32GG_STK3700/GCC_ARM/mpu_interface.elf
	file ./.build/EFM32GG_STK3700/GCC_ARM/mpu_interface.elf
	dir mbed-os/features/FEATURE_UVISOR/importer/TARGET_IGNORE/uvisor
	add-symbol-file debug.elf uvisor_init
	c
